package Vistas;

import Controles.Conexion;
import Controles.TorneoData;
import Modelos.Torneo;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;


public class ListaTorneos extends javax.swing.JInternalFrame {

    private DefaultTableModel modelo  = new DefaultTableModel();
    private ArrayList<Torneo> torneos;
    private ArrayList<Torneo> torneosActivos;
    private TorneoData torneoData;
    private MenuPrincipal1 menu;
    private Conexion conexion = new Conexion();

    public ListaTorneos() {
        initComponents();
        try {
        conexion=new Conexion();
        modelo=new DefaultTableModel();
        
        cursadaData=new CursadaData(conexion);
        listaCursada=(ArrayList)cursadaData.obtenerCursadas();
        
        materiaData=new MateriaData(conexion);
        listaMaterias=(ArrayList)materiaData.obtenerMaterias();
        
        alumnoData=new AlumnoData(conexion);
        listaAlumnos=(ArrayList)alumnoData.obtenerAlumnos();
        
        cargarMaterias();
        armaCabeceraTabla();
        cargarDatos();
        } catch (ClassNotFoundException ex) {
            System.out.println("error" + ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jcbEstado = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtListaAlumMat = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Listado de Torneos");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Estado");

        jcbEstado.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jcbEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbEstadoActionPerformed(evt);
            }
        });

        jtListaAlumMat.setBackground(new java.awt.Color(153, 204, 255));
        jtListaAlumMat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtListaAlumMat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jtListaAlumMat.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(jtListaAlumMat);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel2)
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jcbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jcbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbEstadoActionPerformed
        cargarDatos();
    }//GEN-LAST:event_jcbEstadoActionPerformed

    public void cargarMaterias(){
        
        forjcbEstadoitem:listaMaterias){
            jcbMateria.addItem(item);
        }
    }
    
    public void armaCabeceraTabla(){
    
        ArrayList<Object> columns=new ArrayList<Object>();
        columns.add("IdAlumno");
        columns.add("Apellido");
        columns.add("Nombre");
        columns.add("Nota");
        
        for(Object it:columns){
        
            modelo.addColumn(it);
        }
        
        jtListaAlumMat.setModel(modelo);
    }
    
    public void borrarFilasTabla(){
    
        int a=modelo.getRowCount()-1;
        for (int i = a; i >= 0; i--) {
            modelo.removeRow(i);
            
        }
    }
    
    public void cargarDatos(){
    
        borrarFilasTabljcbEstado   
        Materia mat=(Materia)jcbMateria.getSelectedItem();
        
        for (Cursada m:listaCursada) {
            
            if (m.getMateria().getIdMateria()==mat.getIdMateria()) {                
                modelo.addRow(new Object[]{m.getAlumno().getIdAlumno(),m.getAlumno().getApellido(),m.getAlumno().getNombre(),m.getNota()});
            }
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<Torneos> jcbEstado;
    private javax.swing.JTable jtListaAlumMat;
    // End of variables declaration//GEN-END:variables
}
