/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Controles.Conexion;
import Controles.JugadorData;
import Controles.PatrocinioData;
import Controles.SponsorData;
import Modelos.Jugador;
import Modelos.Patrocinio;
import Modelos.Sponsor;
import java.awt.event.ActionEvent;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author carlo_000
 */
public class VActualizarPatrocinio extends javax.swing.JInternalFrame {

    /**
     * Creates new form VActualizarPatrocinio
     */
    private DefaultTableModel modelo;
    private JugadorData jugadorData;
    private SponsorData sponsorData;

    private ArrayList<Jugador> listaJugadores = new ArrayList<>();
    private ArrayList<Sponsor> listaSponsores = new ArrayList<>();
    ArrayList<Patrocinio> patrocinios = new ArrayList<>();
    Patrocinio patrocinio;
    
    public VActualizarPatrocinio() {
        initComponents();
        modelo = new DefaultTableModel();
        
        armarCabecera();
        llenarTablaPatrocinios();
    }
    private void armarCabecera(){
        ArrayList<Object>columnas = new ArrayList<>();
        columnas.add("Id Patrocinio");
        columnas.add("Sponsor");
        columnas.add("Jugador");
        columnas.add("Activo");
        
        for(Object titulo: columnas){
            modelo.addColumn(titulo);
        }
        jtblPatrocinio.setModel(modelo);
    }
    
     private void borrarFilasTabla(){
    
        int fila = modelo.getRowCount()-1;
        for (int i = fila; i >= 0; i--) {
            modelo.removeRow(i);
            
        }
    }

    private void llenarTablaPatrocinios() {
        borrarFilasTabla();
        Conexion c = new Conexion();
        PatrocinioData pd = new PatrocinioData(c);
        patrocinios = pd.buscarTodosPatrocinio();
        for(Patrocinio pat: patrocinios){
            
           modelo.addRow(new Object[] {pat.getIdPatrocinio(), pat.getSponsor(), pat.getJugador(), pat.isActivo()});
        }
    }
     private void limpiar(){
        jtfId.setText("");
        jtfJugador.setText("");
        jtfSponsor.setText("");
        jcbActivo.setSelected(false);
    }
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jcbActivo = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblPatrocinio = new javax.swing.JTable();
        jbActualizar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jtfId = new javax.swing.JTextField();
        jtfJugador = new javax.swing.JTextField();
        jtfSponsor = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("Actualizar Patrocinio");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Jugador");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Sponsor");

        jcbActivo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jcbActivo.setText("Activo");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Patrocinios por Jugador");

        jtblPatrocinio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtblPatrocinio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtblPatrocinioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtblPatrocinio);

        jbActualizar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbActualizar.setText("Actualizar");
        jbActualizar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbActualizarActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Id Patrocinio");

        jtfId.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtfId.setEnabled(false);

        jtfJugador.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtfJugador.setEnabled(false);

        jtfSponsor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtfSponsor.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(30, 30, 30)
                        .addComponent(jtfId, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfSponsor)
                                    .addComponent(jtfJugador))
                                .addGap(19, 19, 19))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jcbActivo)
                                .addGap(43, 43, 43)
                                .addComponent(jbActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jtfId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtfJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addComponent(jtfSponsor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbActivo)
                    .addComponent(jbActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbActualizarActionPerformed
        // TODO add your handling code here:
       Conexion c = new Conexion();
       JugadorData jd = new JugadorData(c);
       PatrocinioData pd = new PatrocinioData(c);
       boolean activo = jcbActivo.isSelected();
       int id = Integer.parseInt(jtfId.getText());
       Sponsor s = pd.buscarPatrocinio(id).getSponsor();
       Jugador j = pd.buscarPatrocinio(id).getJugador();
       
       Patrocinio p = new Patrocinio(id, s, j, activo);
       pd.actualizarPatrocinio(p);
       borrarFilasTabla();
       llenarTablaPatrocinios();
       limpiar();
    }//GEN-LAST:event_jbActualizarActionPerformed

    private void jtblPatrocinioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtblPatrocinioMouseClicked
        // TODO add your handling code here:
        Conexion c = new Conexion();
        PatrocinioData pd = new PatrocinioData(c);
        int seleccion = jtblPatrocinio.rowAtPoint(evt.getPoint());
        jtfId.setText(String.valueOf(jtblPatrocinio.getValueAt(seleccion,0)));
        jtfJugador.setText(String.valueOf(jtblPatrocinio.getValueAt(seleccion,2)));
        jtfSponsor.setText(String.valueOf(jtblPatrocinio.getValueAt(seleccion,1)));
        int id = Integer.parseInt(jtfId.getText());
        boolean activo = pd.buscarPatrocinio(id).isActivo();
        jcbActivo.setSelected(activo);
       
    }//GEN-LAST:event_jtblPatrocinioMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbActualizar;
    private javax.swing.JCheckBox jcbActivo;
    private javax.swing.JTable jtblPatrocinio;
    private javax.swing.JTextField jtfId;
    private javax.swing.JTextField jtfJugador;
    private javax.swing.JTextField jtfSponsor;
    // End of variables declaration//GEN-END:variables
}
