/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Controles.Conexion;
import Controles.JugadorData;
import Controles.PatrocinioData;
import Controles.SponsorData;
import Modelos.Jugador;
import Modelos.Patrocinio;
import Modelos.Sponsor;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author carlo_000
 */
public class VEliminarPatrocinio extends javax.swing.JInternalFrame {

    /**
     * Creates new form VEliminarPatrocinio
     */
   private DefaultTableModel modelo;
    private JugadorData jugadorData;
    private SponsorData sponsorData;

    private ArrayList<Jugador> listaJugadores = new ArrayList<>();
    private ArrayList<Sponsor> listaSponsores = new ArrayList<>();
    ArrayList<Patrocinio> patrocinios = new ArrayList<>();
    Patrocinio patrocinio;
    
     public VEliminarPatrocinio() {
        initComponents();
        modelo = new DefaultTableModel();
        
        armarCabecera();
        llenarTablaPatrocinios();
    }
    
    private void armarCabecera(){
        ArrayList<Object>columnas = new ArrayList<>();
        columnas.add("Id Patrocinio");
        columnas.add("Sponsor");
        columnas.add("Jugador");
        columnas.add("Activo");
        
        for(Object titulo: columnas){
            modelo.addColumn(titulo);
        }
        jtPatrocinios.setModel(modelo);
    }
    
     private void borrarFilasTabla(){
    
        int fila = modelo.getRowCount()-1;
        for (int i = fila; i >= 0; i--) {
            modelo.removeRow(i);
            
        }
    }

    private void llenarTablaPatrocinios() {
        borrarFilasTabla();
        Conexion c = new Conexion();
        PatrocinioData pd = new PatrocinioData(c);
        patrocinios = pd.buscarTodosPatrocinio();
        for(Patrocinio pat: patrocinios){
            
           modelo.addRow(new Object[] {pat.getIdPatrocinio(), pat.getSponsor(), pat.getJugador(), pat.isActivo()});
        }
    }   
    private void limpiar(){
        jtfId.setText("");
        jtfJugador.setText("");
        jtfSponsor.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtPatrocinios = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jtfId = new javax.swing.JTextField();
        jtfJugador = new javax.swing.JTextField();
        jtfSponsor = new javax.swing.JTextField();
        jbEliminar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Eliminar Patrocinio");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Id Patrocinio");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Jugador");

        jtPatrocinios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jtPatrocinios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtPatrociniosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtPatrocinios);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Sponsor");

        jtfId.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtfId.setEnabled(false);

        jtfJugador.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtfJugador.setEnabled(false);

        jtfSponsor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtfSponsor.setEnabled(false);

        jbEliminar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbEliminar.setText("Eliminar");
        jbEliminar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEliminarActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Lista de patrocinios");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(96, 96, 96)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtfId)
                                    .addComponent(jtfJugador)
                                    .addComponent(jtfSponsor, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(46, 46, 46)
                                        .addComponent(jbEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel5)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jtfJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfSponsor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))))
                .addGap(29, 29, 29)
                .addComponent(jbEliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtPatrociniosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtPatrociniosMouseClicked
        // TODO add your handling code here:
        Conexion c = new Conexion();
        PatrocinioData pd = new PatrocinioData(c);
        int seleccion = jtPatrocinios.rowAtPoint(evt.getPoint());
        jtfId.setText(String.valueOf(jtPatrocinios.getValueAt(seleccion,0)));
        jtfJugador.setText(String.valueOf(jtPatrocinios.getValueAt(seleccion,2)));
        jtfSponsor.setText(String.valueOf(jtPatrocinios.getValueAt(seleccion,1)));
        int id = Integer.parseInt(jtfId.getText());
        boolean activo = pd.buscarPatrocinio(id).isActivo();
    }//GEN-LAST:event_jtPatrociniosMouseClicked

    private void jbEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEliminarActionPerformed
        // TODO add your handling code here:
       Conexion c = new Conexion();
       JugadorData jd = new JugadorData(c);
       PatrocinioData pd = new PatrocinioData(c);
       int id = Integer.parseInt(jtfId.getText());
       
       pd.borrarPatrocinio(id);
       borrarFilasTabla();
       llenarTablaPatrocinios();
       limpiar();
    }//GEN-LAST:event_jbEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbEliminar;
    private javax.swing.JTable jtPatrocinios;
    private javax.swing.JTextField jtfId;
    private javax.swing.JTextField jtfJugador;
    private javax.swing.JTextField jtfSponsor;
    // End of variables declaration//GEN-END:variables
}
