/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

/**
 *
 * @author carlo_000
 */
public class VistaTornTen extends javax.swing.JFrame {

    /**
     * Creates new form VistaTornTen
     */
    public VistaTornTen() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdpEscritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmiFJugador = new javax.swing.JMenuItem();
        jmiLJugadores = new javax.swing.JMenuItem();
        jmiEstadio = new javax.swing.JMenu();
        jmiFEstadio = new javax.swing.JMenuItem();
        jmiListaEstadios = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jmiSponsor = new javax.swing.JMenuItem();
        jmiEliminarS = new javax.swing.JMenuItem();
        jmiActualizarS = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jmiPatrocinio = new javax.swing.JMenuItem();
        jmiActualizar = new javax.swing.JMenuItem();
        jmiEliminar = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jmiLEncuentros = new javax.swing.JMenuItem();
        jmiCrearEncuentro = new javax.swing.JMenuItem();
        jmTorneo1 = new javax.swing.JMenu();
        jmAltaBajaTorneo1 = new javax.swing.JMenu();
        jmConsultaTorneo1 = new javax.swing.JMenu();
        jmiRanking = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jdpEscritorioLayout = new javax.swing.GroupLayout(jdpEscritorio);
        jdpEscritorio.setLayout(jdpEscritorioLayout);
        jdpEscritorioLayout.setHorizontalGroup(
            jdpEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 719, Short.MAX_VALUE)
        );
        jdpEscritorioLayout.setVerticalGroup(
            jdpEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 595, Short.MAX_VALUE)
        );

        jMenu1.setText("Jugador");

        jmiFJugador.setText("Formulario Jugador");
        jmiFJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiFJugadorActionPerformed(evt);
            }
        });
        jMenu1.add(jmiFJugador);

        jmiLJugadores.setText("Lista de Jugadores");
        jmiLJugadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiLJugadoresActionPerformed(evt);
            }
        });
        jMenu1.add(jmiLJugadores);

        jMenuBar1.add(jMenu1);

        jmiEstadio.setText("Estadio");

        jmiFEstadio.setText("Formulario Estadio");
        jmiFEstadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiFEstadioActionPerformed(evt);
            }
        });
        jmiEstadio.add(jmiFEstadio);

        jmiListaEstadios.setText("Lista de Estadios");
        jmiListaEstadios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiListaEstadiosActionPerformed(evt);
            }
        });
        jmiEstadio.add(jmiListaEstadios);

        jMenuBar1.add(jmiEstadio);

        jMenu3.setText("Sponsor");
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });

        jmiSponsor.setText("Registrar Sponsor");
        jmiSponsor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiSponsorActionPerformed(evt);
            }
        });
        jMenu3.add(jmiSponsor);

        jmiEliminarS.setText("Eliminar Sponsor");
        jmiEliminarS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiEliminarSActionPerformed(evt);
            }
        });
        jMenu3.add(jmiEliminarS);

        jmiActualizarS.setText("Actualizar Sponsor");
        jmiActualizarS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiActualizarSActionPerformed(evt);
            }
        });
        jMenu3.add(jmiActualizarS);

        jMenuBar1.add(jMenu3);

        jMenu4.setText(" Patrocinio");

        jmiPatrocinio.setText("Agregar Patrocinio");
        jmiPatrocinio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPatrocinioActionPerformed(evt);
            }
        });
        jMenu4.add(jmiPatrocinio);

        jmiActualizar.setText("Activar/Desactivar ");
        jmiActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiActualizarActionPerformed(evt);
            }
        });
        jMenu4.add(jmiActualizar);

        jmiEliminar.setText("Eliminar");
        jmiEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiEliminarActionPerformed(evt);
            }
        });
        jMenu4.add(jmiEliminar);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Encuentro");
        jMenu5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu5ActionPerformed(evt);
            }
        });

        jmiLEncuentros.setText("Actualizar Encuentro");
        jmiLEncuentros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiLEncuentrosActionPerformed(evt);
            }
        });
        jMenu5.add(jmiLEncuentros);

        jmiCrearEncuentro.setText("Crear Encuentro");
        jmiCrearEncuentro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCrearEncuentroActionPerformed(evt);
            }
        });
        jMenu5.add(jmiCrearEncuentro);

        jMenuBar1.add(jMenu5);

        jmTorneo1.setText("Torneo");

        jmAltaBajaTorneo1.setText("Alta/Baja");
        jmAltaBajaTorneo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmAltaBajaTorneo1MouseClicked(evt);
            }
        });
        jmAltaBajaTorneo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmAltaBajaTorneo1ActionPerformed(evt);
            }
        });
        jmTorneo1.add(jmAltaBajaTorneo1);

        jmConsultaTorneo1.setText("Consulta");
        jmConsultaTorneo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmConsultaTorneo1MouseClicked(evt);
            }
        });
        jmTorneo1.add(jmConsultaTorneo1);

        jmiRanking.setText("Ranking");
        jmiRanking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiRankingActionPerformed(evt);
            }
        });
        jmTorneo1.add(jmiRanking);

        jMenuBar1.add(jmTorneo1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jdpEscritorio)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jdpEscritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiFEstadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiFEstadioActionPerformed
        // TODO add your handling code here:
        jdpEscritorio.removeAll();
        jdpEscritorio.repaint();
        VEstadio ve = new VEstadio();
        ve.setVisible(true);
        jdpEscritorio.add(ve);
    }//GEN-LAST:event_jmiFEstadioActionPerformed

    private void jmiFJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiFJugadorActionPerformed
        // TODO add your handling code here:
        jdpEscritorio.removeAll();
        jdpEscritorio.repaint();
        VJugador vj = new VJugador();
        vj.setVisible(true);
        jdpEscritorio.add(vj);
    }//GEN-LAST:event_jmiFJugadorActionPerformed

    private void jmAltaBajaTorneo1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmAltaBajaTorneo1MouseClicked
        jdpEscritorio.removeAll();
        jdpEscritorio.repaint();
        VTorneo aC=new VTorneo();
        aC.setVisible(true);
        jdpEscritorio.add(aC);
        jdpEscritorio.moveToFront(aC);
    }//GEN-LAST:event_jmAltaBajaTorneo1MouseClicked

    private void jmAltaBajaTorneo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmAltaBajaTorneo1ActionPerformed

    }//GEN-LAST:event_jmAltaBajaTorneo1ActionPerformed

    private void jmConsultaTorneo1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmConsultaTorneo1MouseClicked
        jdpEscritorio.removeAll();
        jdpEscritorio.repaint();
        ListaTorneos aC=new ListaTorneos();
        aC.setVisible(true);
        jdpEscritorio.add(aC);
        jdpEscritorio.moveToFront(aC);
    }//GEN-LAST:event_jmConsultaTorneo1MouseClicked

    private void jmiLJugadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiLJugadoresActionPerformed
        jdpEscritorio.removeAll();
        jdpEscritorio.repaint();
        ListaJugadores aC=new ListaJugadores();
        aC.setVisible(true);
        jdpEscritorio.add(aC);
        jdpEscritorio.moveToFront(aC);
    }//GEN-LAST:event_jmiLJugadoresActionPerformed

    private void jmiSponsorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiSponsorActionPerformed
        // TODO add your handling code here:
        jdpEscritorio.removeAll();
        jdpEscritorio.repaint();
        VSponsor vs = new VSponsor();
        vs.setVisible(true);
        jdpEscritorio.add(vs);
    }//GEN-LAST:event_jmiSponsorActionPerformed

    private void jmiPatrocinioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPatrocinioActionPerformed
        // TODO add your handling code here:
        jdpEscritorio.removeAll();
        jdpEscritorio.repaint();
        Patrocinios p = new Patrocinios();
        p.setVisible(true);
        jdpEscritorio.add(p);
        jdpEscritorio.moveToFront(p);
    }//GEN-LAST:event_jmiPatrocinioActionPerformed

    private void jmiActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiActualizarActionPerformed
        // TODO add your handling code here:
        jdpEscritorio.removeAll();
        jdpEscritorio.repaint();
        VActualizarPatrocinio vap = new VActualizarPatrocinio();
        vap.setVisible(true);
        jdpEscritorio.add(vap);
        jdpEscritorio.moveToFront(vap);
    }//GEN-LAST:event_jmiActualizarActionPerformed

    private void jmiEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiEliminarActionPerformed
        // TODO add your handling code here:
        jdpEscritorio.removeAll();
        jdpEscritorio.repaint();
        VEliminarPatrocinio vep = new VEliminarPatrocinio();
        vep.setVisible(true);
        jdpEscritorio.add(vep);
        jdpEscritorio.moveToFront(vep);
    }//GEN-LAST:event_jmiEliminarActionPerformed

    private void jmiLEncuentrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiLEncuentrosActionPerformed
        // TODO add your handling code here:
        jdpEscritorio.removeAll();
        jdpEscritorio.repaint();
        VActualizarEncuentro vae = new VActualizarEncuentro();
        vae.setVisible(true);
        jdpEscritorio.add(vae);
        jdpEscritorio.moveToFront(vae);
    }//GEN-LAST:event_jmiLEncuentrosActionPerformed

    private void jmiCrearEncuentroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCrearEncuentroActionPerformed
        // TODO add your handling code here:
        jdpEscritorio.removeAll();
        jdpEscritorio.repaint();
        VCrearEncuentro vce = new VCrearEncuentro();
        vce.setVisible(true);
        jdpEscritorio.add(vce);
        jdpEscritorio.moveToFront(vce);
    }//GEN-LAST:event_jmiCrearEncuentroActionPerformed

    private void jMenu5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu5ActionPerformed

    private void jmiListaEstadiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiListaEstadiosActionPerformed
        // TODO add your handling code here:
        jdpEscritorio.removeAll();
        jdpEscritorio.repaint();
        ListaEstadios le = new ListaEstadios();
        le.setVisible(true);
        jdpEscritorio.add(le);
        jdpEscritorio.moveToFront(le);
    }//GEN-LAST:event_jmiListaEstadiosActionPerformed

    private void jmiRankingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiRankingActionPerformed
        // TODO add your handling code here:
        jdpEscritorio.removeAll();
        jdpEscritorio.repaint();
        VRanking vr = new VRanking();
        vr.setVisible(true);
        jdpEscritorio.add(vr);
        jdpEscritorio.moveToFront(vr);
    }//GEN-LAST:event_jmiRankingActionPerformed

    private void jmiEliminarSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiEliminarSActionPerformed
        // TODO add your handling code here:
        jdpEscritorio.removeAll();
        jdpEscritorio.repaint();
        VEliminarSponsor ves = new VEliminarSponsor();
        ves.setVisible(true);
        jdpEscritorio.add(ves);
        jdpEscritorio.moveToFront(ves);
    }//GEN-LAST:event_jmiEliminarSActionPerformed

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu3ActionPerformed

    private void jmiActualizarSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiActualizarSActionPerformed
        // TODO add your handling code here:
        jdpEscritorio.removeAll();
        jdpEscritorio.repaint();
        VActualizarSponsor vas = new VActualizarSponsor();
        vas.setVisible(true);
        jdpEscritorio.add(vas);
        jdpEscritorio.moveToFront(vas);
    }//GEN-LAST:event_jmiActualizarSActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaTornTen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaTornTen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaTornTen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaTornTen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaTornTen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JDesktopPane jdpEscritorio;
    private javax.swing.JMenu jmAltaBajaTorneo1;
    private javax.swing.JMenu jmConsultaTorneo1;
    private javax.swing.JMenu jmTorneo1;
    private javax.swing.JMenuItem jmiActualizar;
    private javax.swing.JMenuItem jmiActualizarS;
    private javax.swing.JMenuItem jmiCrearEncuentro;
    private javax.swing.JMenuItem jmiEliminar;
    private javax.swing.JMenuItem jmiEliminarS;
    private javax.swing.JMenu jmiEstadio;
    private javax.swing.JMenuItem jmiFEstadio;
    private javax.swing.JMenuItem jmiFJugador;
    private javax.swing.JMenuItem jmiLEncuentros;
    private javax.swing.JMenuItem jmiLJugadores;
    private javax.swing.JMenuItem jmiListaEstadios;
    private javax.swing.JMenuItem jmiPatrocinio;
    private javax.swing.JMenuItem jmiRanking;
    private javax.swing.JMenuItem jmiSponsor;
    // End of variables declaration//GEN-END:variables
}
